### ISSUE TITLE
Engine transport out of tempo when changing tempo during a beat

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/mentat#1]
Transport becomes inconsistent if I change the tempo while playing. Probably if tempo is changed while Module.wait() is running.
I perfectly understand that it may be quite complex because the running timers should have to be stopped/relaunched if tempo is changed. However, do you think it would be very hard to do ? I may make a PR if it is doable.

**Comment by jean-emmanuel** [comment]
Closing as completed.
