### ISSUE TITLE
animate parameter with null duration makes it crash 

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/mentat#3]
animate() method makes ZeroDivision error if we set the duration to 0.0.
Would it be reasonable to treat an animate() with duration <= 0.0 as a set() ? (I mean, set directly the parameter value).

**Comment by jean-emmanuel** [comment]
Thanks, it's fixed now.

> Would it be reasonable to treat an animate() with duration <= 0.0 as a set() ?

I kept things in the animate() route for consistency.

**Comment by Houston4444** [comment]
waouw ! Thanks for this very fast fix.
